package posra.dataaccess;

// Generated Jun 22, 2014 10:16:50 PM by Hibernate Tools 4.0.0

/**
 * SegmentAssociation generated by hbm2java
 */
public class SegmentAssociation implements java.io.Serializable {

	private SegmentAssociationId id;
	private Segment segmentBySegmentId2;
	private Segment segmentBySegmentId1;
	private Polymer polymer;
	private String relationshipType;

	public SegmentAssociation() {
	}

	public SegmentAssociation(SegmentAssociationId id,
			Segment segmentBySegmentId2, Segment segmentBySegmentId1,
			Polymer polymer, String relationshipType) {
		this.id = id;
		this.segmentBySegmentId2 = segmentBySegmentId2;
		this.segmentBySegmentId1 = segmentBySegmentId1;
		this.polymer = polymer;
		this.relationshipType = relationshipType;
	}

	public SegmentAssociationId getId() {
		return this.id;
	}

	public void setId(SegmentAssociationId id) {
		this.id = id;
	}

	public Segment getSegmentBySegmentId2() {
		return this.segmentBySegmentId2;
	}

	public void setSegmentBySegmentId2(Segment segmentBySegmentId2) {
		this.segmentBySegmentId2 = segmentBySegmentId2;
	}

	public Segment getSegmentBySegmentId1() {
		return this.segmentBySegmentId1;
	}

	public void setSegmentBySegmentId1(Segment segmentBySegmentId1) {
		this.segmentBySegmentId1 = segmentBySegmentId1;
	}

	public Polymer getPolymer() {
		return this.polymer;
	}

	public void setPolymer(Polymer polymer) {
		this.polymer = polymer;
	}

	public String getRelationshipType() {
		return this.relationshipType;
	}

	public void setRelationshipType(String relationshipType) {
		this.relationshipType = relationshipType;
	}

}
