package posra.dataaccess;

// Generated Jun 22, 2014 10:16:50 PM by Hibernate Tools 4.0.0

/**
 * SegmentAssociationId generated by hbm2java
 */
public class SegmentAssociationId implements java.io.Serializable {

	private int segmentAssociationId;
	private int polymerId;
	private int segmentId1;
	private int segmentId2;

	public SegmentAssociationId() {
	}

	public SegmentAssociationId(int segmentAssociationId, int polymerId,
			int segmentId1, int segmentId2) {
		this.segmentAssociationId = segmentAssociationId;
		this.polymerId = polymerId;
		this.segmentId1 = segmentId1;
		this.segmentId2 = segmentId2;
	}

	public int getSegmentAssociationId() {
		return this.segmentAssociationId;
	}

	public void setSegmentAssociationId(int segmentAssociationId) {
		this.segmentAssociationId = segmentAssociationId;
	}

	public int getPolymerId() {
		return this.polymerId;
	}

	public void setPolymerId(int polymerId) {
		this.polymerId = polymerId;
	}

	public int getSegmentId1() {
		return this.segmentId1;
	}

	public void setSegmentId1(int segmentId1) {
		this.segmentId1 = segmentId1;
	}

	public int getSegmentId2() {
		return this.segmentId2;
	}

	public void setSegmentId2(int segmentId2) {
		this.segmentId2 = segmentId2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SegmentAssociationId))
			return false;
		SegmentAssociationId castOther = (SegmentAssociationId) other;

		return (this.getSegmentAssociationId() == castOther
				.getSegmentAssociationId())
				&& (this.getPolymerId() == castOther.getPolymerId())
				&& (this.getSegmentId1() == castOther.getSegmentId1())
				&& (this.getSegmentId2() == castOther.getSegmentId2());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSegmentAssociationId();
		result = 37 * result + this.getPolymerId();
		result = 37 * result + this.getSegmentId1();
		result = 37 * result + this.getSegmentId2();
		return result;
	}

}
